---
title: "GitHub"
author: "Alex Gregory"
date: "2022-12-03"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Import Packages
```{r echo=FALSE, message=FALSE, warning=FALSE}
library(ggplot2)
library(tidyr)
library(forcats)
library(ape)
library(dplyr)
library(boot)
library(epitools)
library(broom)
library(infer)
library(raster)
library(sp)
library(mltools)
library(FSA)
library(car)
library(gtsummary)
library(rstatix)
library(rcompanion)
library(ggpubr)
library(vegan)
library(rstatix)
library(gtsummary)
library(RVAideMemoire)
library(rcompanion)
library(stargazer)
library(gt)
library(sjPlot)
library(viridis)
library(pwr2)
library(plyr)
library(coxed)
```



```{r}
# Import data
df.data <- read.csv("~/LithicProcurementProject/Seh 2016 survey recording system_complete_03.17.17.csv", header=T)

# Remove previously identified quarries from new surveyed areas
df.data <- df.data[-c(which(df.data$survey_square_id=="Chert outcrop 2" |
                        df.data$survey_square_id=="calcite sample" |
                          df.data$survey_square_id=="Dolerite outcrop" |
                          df.data$survey_square_id=="Chert quarry sehonghong village" |
                          df.data$survey_square_id=="dolerite sample" |
                          df.data$survey_square_id=="Hornfels sample" |
                          df.data$survey_square_id=="Seh-a" |
                          df.data$survey_square_id=="Seh-b" |
                          df.data$survey_square_id=="Seh-c" |
                          df.data$survey_square_id=="Seh-d" |
                          df.data$survey_square_id=="Seh-e" |
                          df.data$survey_square_id=="SEH-chert outcrop 3")),]


# Subset the data based upon only the lithics recorded at Sehonghong
df.land <- df.data |>
  select(survey_square_id, Location, Latitude_x_min, Longitude_y_min, Raw.material.type,
         Length, Width, Thickness, Mass)

colnames(df.land) <- c("ID", "Environment", "x", "y", "Lithic", "Length", "Width", "Thickness", "Mass")

df.land[which(df.land$Lithic=="agate"), "Lithic"] <- "Agate"
df.land[which(df.land$Lithic=="coarse chert"), "Lithic"] <- "CoarseChert"
df.land[which(df.land$Lithic=="crystal quartz"), "Lithic"] <- "CrystallineQuartz"
df.land[which(df.land$Lithic=="dolerite" | df.land$Lithic=="Dolerite"), "Lithic"] <- "Dolerite"
df.land[which(df.land$Lithic=="fine chert" | df.land$Lithic=="Fine chert"), "Lithic"] <- "Fine Chert"
df.land[which(df.land$Lithic=="quartzite"), "Lithic"] <- "Quartzite"
df.land[which(df.land$Lithic=="sandstone"), "Lithic"] <- "Sandstone"

df.land <- df.land |>
  dplyr::filter(Lithic %in% c("Agate", "CoarseChert", "CrystallineQuartz", "Dolerite", "Fine Chert", "Quartzite", "Sandstone"))

# Calculate the volume for all nodules
df.data$V <- (4/3)*pi*(df.data$Length/2)*(df.data$Width/2)*(df.data$Thickness/2)

# Calculate surface area for all nodules
p=1.6075 # Exponent for elliptical surface area
df.data$SA <- 4*pi*((((((df.data$Length/2)^p)*((df.data$Width/2)^p)) +
                            ((((df.data$Length/2)^p)*((df.data$Thickness/2)^p))) +
                            ((((df.data$Width/2)^p)*((df.data$Thickness/2)^p))))/3)^(1/p))


```

## Import Sehonghong Data
```{r echo=FALSE}
#import flake data
df.flake <- 
  read.csv("C:/Users/grego/OneDrive/Documents/LithicProcurementProject/SehonghongCores/sehonghong_flakes.csv", header=T)
data.flake <- df.flake[,c(4,6,11,12,66:73,77,82)]
data.flake <- data.flake[which(data.flake$RawMaterial=="Agate"|
                    data.flake$RawMaterial=="CoarseChert"|
                    data.flake$RawMaterial=="CrystallineQuartz"|
                    data.flake$RawMaterial=="Dolerite"|
                    data.flake$RawMaterial=="FineChert"|
                    data.flake$RawMaterial=="Quartzite"|
                    data.flake$RawMaterial=="Sandstone"),]
#data.flake$RawMaterial <- droplevels(data.flake$RawMaterial)

# COmbine rbl and clbrf
data.flake$Level <- as.character(data.flake$Level)

data.flake$Level[data.flake$Level=="rbl"|
                         data.flake$Level=="clbrf"] <- "rbl-clbrf"

data.flake <- data.flake[which(data.flake$Level=="barf" |
                                 data.flake$Level=="bas" |
                                 data.flake$Level=="rbl-clbrf" |
                                 data.flake$Level=="rf"),]
data.flake$Level <- as.factor(data.flake$Level)

# Import core data
df.core <- 
  read.csv("C:/Users/grego/OneDrive/Documents/LithicProcurementProject/SehonghongCores/sehonghong_cores.csv", header=T)

data.core <- df.core[,c(5,7:8,13:16,76:79,82)]
data.core <- data.core[which(data.core$RawMaterial=="Agate"|
                    data.core$RawMaterial=="CoarseChert"|
                    data.core$RawMaterial=="CrystallineQuartz"|
                    data.core$RawMaterial=="Dolerite"|
                    data.core$RawMaterial=="FineChert"|
                    data.core$RawMaterial=="Quartzite"|
                    data.core$RawMaterial=="Sandstone"),]

#data.core$RawMaterial <- droplevels(data.core$RawMaterial)

# COmbine rbl and clbrf
data.core$Level <- as.character(data.core$Level)
data.core$Level[which(data.core$Level=="rbl"|
                         data.core$Level=="clbrf")] <- "rbl-clbrf"

data.core <- data.core[which(data.core$Level=="barf" |
                                 data.core$Level=="bas" |
                                 data.core$Level=="rbl-clbrf" |
                                 data.core$Level=="rf"),]
data.core$Level <- as.factor(data.core$Level)

```

# Description of Sehonghong Data
```{r}
df.flake |> 
  dplyr::group_by(CortexArea) |>
  dplyr::select(CortexArea) |>
  mutate(CortexArea = factor(CortexArea, levels=c("0%","1-9%", "11-40%","61-90%", "41-60%", "91-99%","100%"))) |>
  dplyr::summarize(count=n()) -> seh_cortex

ggplot(seh_cortex, aes(x=CortexArea, y=count)) +
  geom_bar(stat="identity")

df.core |> 
    dplyr::group_by(CortexRoundness, Level) |>
    dplyr::select(CortexRoundness) |>
    dplyr::summarize(count=n()) -> seh_cortex

ggplot(seh_cortex[-1,], aes(x=CortexRoundness, y=count)) +
  geom_bar(stat="identity")
```





# Description of Landscape Survey
```{r message=FALSE, warning=FALSE, include=FALSE}
df.land |>
  dplyr::select(Lithic, Environment, Mass) |>
  dplyr::group_by(Lithic, Environment) |>
  dplyr::mutate(Mass = ifelse(is.na(Mass), 0, Mass)) |>
  dplyr::summarise(Mass = sum(Mass)) -> gplot

p <- ggplot(df.land, aes(x=log(Mass), y=Lithic, fill=Environment))+
  geom_point(position = position_jitterdodge()) + geom_boxplot(aes(alpha=.7))
p + scale_fill_manual(values=c("#3399FF", "#996633"))
```

## Compute ANOVA for Mass as a Function of Lithic Material and Environment
```{r}
# Model 1
aov1 <- aov(lm.land <- lm(log(Mass)~Lithic*Environment, data=df.land))
summary(aov1)

# Pairwise comparison
tuk.aov1 <- TukeyHSD(aov1)
round(tuk.aov1$`Lithic:Environment`[which(tuk.aov1$`Lithic:Environment`[,4]<.05),],3)

# Simple count data for observation per raw material and environment and survey area (ID)
df.land %>%
  dplyr::group_by(Lithic, Environment, ID) %>%
  dplyr::summarise(count=n())
```

## Compare Survey Data to Sehonghong Flakes
```{r}
# COmpute proportions of lithic material by environment (landscape survey)
land.table <- table(df.land$Lithic, df.land$Environment)
land.prop <- round(prop.table(land.table,2),3)

# COmpute proportions of lithic by excavation level
flake.table <- table(data.flake$RawMaterial, data.flake$Level)
flake.prop <- round(prop.table(flake.table,2),3)

# COmbine above two proportions
prop.flake_land <- as.data.frame(cbind(land.prop, flake.prop))
prop.flake_land$Lithic <- rownames(land.prop)

# Rearrange levels for stratigraphic ordering
prop.flake_land <- prop.flake_land[,c(1:2,4,5,6,3,7)]

prop.flake_land <- gather(prop.flake_land, "Context", "Proportion",c(Riverine, Terrestrial, barf, bas, `rbl-clbrf`, rf))
#prop.flake_land$Context <- as.factor(prop.flake_land$Context)
prop.flake_land$Context <- factor(prop.flake_land$Context, levels=c("Riverine", "Terrestrial",
                                                                    "bas", "rbl-clbrf",
                                                                    "rf", "barf"))


# Stacked plot with lithic as grouping variable

ggplot(prop.flake_land[1:14,], aes(x=as.factor(Context), y=Proportion, fill=Lithic)) +
  geom_bar(position="stack", stat="identity", colour="black") +
  xlab("Context") +
  scale_fill_viridis_d(option="turbo", direction=-1)+
  theme(legend.title=element_blank(), text=element_text(size=20))

ggplot(prop.flake_land, aes(x=as.factor(Context), y=Proportion, fill=Lithic)) +
  geom_bar(position="stack", stat="identity", colour="black") +
  xlab("Context") +
  scale_fill_viridis_d(option="turbo", direction=-1)+
  theme(text=element_text(size=15))+
  theme(legend.title=element_blank())+
  scale_x_discrete(labels=c("bas"="BAS", "rbl-clbrf"= "RBL-CLBRF","rf"= "RF","barf"= "BARF"))

#########################################
#proportion testing
#########################################
land.t <- land.table[1:7]
land.r <- land.table[8:14]

land.dat <- data.frame("Riverine"=land.r,
                       "Terrestrial"=land.t,
                       "barf"=flake.table[1:7],
                       "bas"=flake.table[8:14],
                       "rbl-clbrf"=flake.table[15:21],
                       "rf"=flake.table[22:28])

land.dat_tbl <- as.table(rbind(c(34, 16, 3, 3, 1, 2),
                               c(0, 19, 29, 16, 13, 16),
                               c(3, 0, 44, 12, 10, 21),
                               c(132, 85, 28, 59, 36, 56),
                               c(3, 21, 201, 138, 194, 140),
                               c(6, 92, 0, 2, 10, 15),
                               c(171, 63, 0, 4, 6, 1)))
rnames <- rownames(land.table)
cnames <- colnames(land.dat)
dimnames(land.dat_tbl) <- list(Material = rnames,
                               Context = cnames)

# Test for difference in raw material frequency
chisq.test(land.dat_tbl)
# Pairwise test
chisq.posthoc.test::chisq.posthoc.test(land.dat_tbl)
```

## Compare Survey Data to Sehonghong Cores
```{r}

# Compute proportions of lithic material by environment (landscape survey)
land.table <- table(df.land$Lithic, df.land$Environment)
land.prop <- round(prop.table(land.table,2),3)

# Compute proportions of lithic by excavation level
core.table <- table(data.core$RawMaterial, data.core$Level)
core.prop <- round(prop.table(core.table,2),3)
core.prop <- core.prop[-6,]

rownames(core.prop) <- rownames(land.prop[-c(6:7),])

# Combine above two proportions
prop.core_land <- as.data.frame(cbind(land.prop[-c(6:7),], core.prop))

# Add back in proportions of 
prop.core_land <- rbind(prop.core_land, c(.032, .150, rep(0,4)))
prop.core_land <- rbind(prop.core_land, c(.858, .271, rep(0,4)))
rownames(prop.core_land) <- rownames(land.prop)

prop.core_land$Lithic <- rownames(land.prop)



# Rearrange levels for stratigraphic ordering
prop.core_land <- prop.core_land[,c(1:2,4,5,6,3,7)]

prop.core_land <- gather(prop.core_land, "Context", "Proportion",c(Riverine, Terrestrial, barf, bas, `rbl-clbrf`, rf))
#prop.core_land$Context <- as.factor(prop.core_land$Context)
prop.core_land$Context <- factor(prop.core_land$Context, levels=c("Riverine", "Terrestrial",
                                                                    "bas", "rbl-clbrf",
                                                                    "rf", "barf"))

# Stacked plot with lithic as grouping variable
ggplot(prop.core_land, aes(x=as.factor(Context), y=Proportion, fill=Lithic)) +
  geom_bar(position="stack", stat="identity", colour="black") +
  xlab("Context") +
  scale_fill_viridis_d(option="turbo", direction=-1)+
  theme(text=element_text(size=15))+
  theme(legend.title=element_blank()) + 
  scale_x_discrete(labels=c("bas"="BAS", "rbl-clbrf"= "RBL-CLBRF","rf"= "RF","barf"= "BARF"))

#########################
# Stats
########################
land.dat_tbl <- as.table(rbind(c(34, 16, 0, 3, 3, 1),
                               c(0, 19, 3, 4, 5, 6),
                               c(3, 0, 5, 1, 2, 21),
                               c(132, 85, 0, 1, 2, 0),
                               c(3, 21, 4, 61, 74, 24),
                               c(6, 92, 0, 0, 0, 0),
                               c(171, 63, 0, 0, 0, 0)))
rnames <- rownames(land.table)
cnames <- colnames(land.dat)
dimnames(land.dat_tbl) <- list(Material = rnames,
                               Context = cnames)

# Test for differences in frequency
## Fisher's test is used because many values hav 0-entries
fisher_test(land.dat_tbl, simulate.p.value = T)

# Pairwise test
## Fisher's only accepts 2 dimensions at a time
c <- 0
for(i in 1:5){
  for(j in 2:(6-c)){  
    print(pairwise_fisher_test(land.dat_tbl[, c(i, j+c)], simulate.p.value=T))
  }
  c <- c + 1
}
```



